package com.asurion.bo.sb.customermanagement.dto;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-12-12T17:22:03.301-06:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://dto.customermanagement.sb.bo.asurion.com/", name = "CreateCustomerPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CreateCustomerPortType {

    @WebMethod(operationName = "CreateCustomer")
    @WebResult(name = "CreateCustomerResponse", targetNamespace = "http://dto.customermanagement.sb.bo.asurion.com/", partName = "response")
    public CreateCustomerResponse createCustomer(
        @WebParam(partName = "request", name = "CreateCustomerRequest", targetNamespace = "http://dto.customermanagement.sb.bo.asurion.com/")
        CreateCustomerRequest request
    );
}
