package com.asurion.bo.sb.customermanagement.dto;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-12-12T17:22:03.314-06:00
 * Generated source version: 3.1.7
 * 
 */
@WebServiceClient(name = "CustomerManagementService", 
                  wsdlLocation = "file:/D:/Workspace/EclipseEE/CustomerManagement/WebContent/WEB-INF/wsdl/CustomerManagement.wsdl",
                  targetNamespace = "http://dto.customermanagement.sb.bo.asurion.com/") 
public class CustomerManagementService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://dto.customermanagement.sb.bo.asurion.com/", "CustomerManagementService");
    public final static QName GetCustomerPortType = new QName("http://dto.customermanagement.sb.bo.asurion.com/", "GetCustomerPortType");
    public final static QName CreateCustomerPortType = new QName("http://dto.customermanagement.sb.bo.asurion.com/", "CreateCustomerPortType");
    public final static QName GetAllCustomersPortType = new QName("http://dto.customermanagement.sb.bo.asurion.com/", "GetAllCustomersPortType");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/Workspace/EclipseEE/CustomerManagement/WebContent/WEB-INF/wsdl/CustomerManagement.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CustomerManagementService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/Workspace/EclipseEE/CustomerManagement/WebContent/WEB-INF/wsdl/CustomerManagement.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CustomerManagementService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CustomerManagementService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CustomerManagementService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public CustomerManagementService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CustomerManagementService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CustomerManagementService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns GetCustomerPortType
     */
    @WebEndpoint(name = "GetCustomerPortType")
    public GetCustomerPortType getGetCustomerPortType() {
        return super.getPort(GetCustomerPortType, GetCustomerPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetCustomerPortType
     */
    @WebEndpoint(name = "GetCustomerPortType")
    public GetCustomerPortType getGetCustomerPortType(WebServiceFeature... features) {
        return super.getPort(GetCustomerPortType, GetCustomerPortType.class, features);
    }


    /**
     *
     * @return
     *     returns CreateCustomerPortType
     */
    @WebEndpoint(name = "CreateCustomerPortType")
    public CreateCustomerPortType getCreateCustomerPortType() {
        return super.getPort(CreateCustomerPortType, CreateCustomerPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CreateCustomerPortType
     */
    @WebEndpoint(name = "CreateCustomerPortType")
    public CreateCustomerPortType getCreateCustomerPortType(WebServiceFeature... features) {
        return super.getPort(CreateCustomerPortType, CreateCustomerPortType.class, features);
    }


    /**
     *
     * @return
     *     returns GetAllCustomersPortType
     */
    @WebEndpoint(name = "GetAllCustomersPortType")
    public GetAllCustomersPortType getGetAllCustomersPortType() {
        return super.getPort(GetAllCustomersPortType, GetAllCustomersPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetAllCustomersPortType
     */
    @WebEndpoint(name = "GetAllCustomersPortType")
    public GetAllCustomersPortType getGetAllCustomersPortType(WebServiceFeature... features) {
        return super.getPort(GetAllCustomersPortType, GetAllCustomersPortType.class, features);
    }

}
