package com.asurion.bo.sb.customermanagement.dto;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-12-12T17:22:03.307-06:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://dto.customermanagement.sb.bo.asurion.com/", name = "GetAllCustomersPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface GetAllCustomersPortType {

    @WebMethod(operationName = "GetAllCustomers")
    @WebResult(name = "GetAllCustomersResponse", targetNamespace = "http://dto.customermanagement.sb.bo.asurion.com/", partName = "response")
    public GetAllCustomersResponse getAllCustomers(
        @WebParam(partName = "request", name = "GetAllCustomersRequest", targetNamespace = "http://dto.customermanagement.sb.bo.asurion.com/")
        GetAllCustomersRequest request
    );
}
